// Addresses of the old WordPress site on iliaedu.ge -> pages of this site,
// so links in Google results and old posts keep working after the move.
// React Router ignores trailing slashes, so '/partniorebi' also matches '/partniorebi/'.
export const LEGACY_REDIRECTS: Record<string, string> = {
  '/en/home': '/',
  '/chvens-shesakheb': '/about',
  '/partniorebi': '/about/partners',
  '/samoqmedo-gegmebi': '/about/strategic/action-plans',
  '/samoqmedo-gegmebis-shesrulebis-angarishebi': '/about/strategic/action-reports',
  '/ganvitarebis-strategiuli-gegma': '/about/strategic/plan',
  '/diplomis-da-sertifikatis-nimushebi': '/about/documents',
  '/profesiuli-saganmanatlebos-prgramebis-catalogi': '/programs-catalog',
  '/profesiuli-saganmanatlebo-programebi': '/programs',
  '/iliaedu-programss': '/programs',
  '/programss/administrative': '/programs/administrative-services',
  '/programss/finance': '/programs/financial-services',
  '/programss/finances': '/programs/financial-services',
  '/programss/ფარმაცია': '/programs/pharmacy',
  '/programss/ვეტერინარია': '/programs/veterinary-medicine',
  '/programss/ინფორმაციული-ტექნოლოგიე': '/programs/information-technology',
  '/programss/ბაგა-ბაღის-აღმზრდელი': '/programs/early-childhood-education',
  '/programss/ბუღალტერია': '/programs/financial-services',
  '/programss/*': '/programs',
  '/siakhleebi': '/news',
  '/სასიხარულო-ამბავი': '/news/authorization-2026',
  '/ჩვენი-საუკეთესოები': '/news/master-teacher-2025-award',
  '/25252025-2': '/news/college-25th-anniversary-celebration-2025',
  '/2-დეკემბერს-ილია-ჭავჭავაძ': '/news/cybersecurity-and-ai-workshop-2025',
  '/category/*': '/news',
  '/galleria': '/gallery',
  '/el-wignebi': '/library',
  '/khshirad-dasmuli-kitxvebi': '/contact',
  '/studentebi': '/',
  '/konpidencialurobis-politika': '/'
};
